---
development:
  enhance_image_tag: true
  static_file_support: false
production:
  enhance_image_tag: true
  static_file_support: true
test:
  enhance_image_tag: true
  static_file_support: false
